void new1()
{
    
    TFile *f2 = TFile::Open("def_1000evts_PXDredON_FullTrackingValidationBkg.root");
    TH1D *h2 = (TH1D*)f2->Get("FullBkg_finding_efficiency_by_phi");
    //TH1D *h2= (TH1D*)f2->Get("FullBkg_finding_efficiency_by_theta");
    //TH1D *h2= (TH1D*)f2->Get("FullBkg_hit_efficiency_with_matched_tracks_by_phi");
    //TH1D *h2= (TH1D*)f2->Get("FullBkg_hit_efficiency_with_matched_tracks_by_theta");
    //TH1D *h2= (TH1D*)f2->Get("FullBkg_finding_and_charge_efficiency_for_primary_tracks_by_phi");
    //TH1D *h2= (TH1D*)f2->Get("expert/FullBkg_z0_res_resolution");
    //TH1D *h2= (TH1D*)f2->Get("expert/FullBkg_d0_estimates");
    //TH1D *h2= (TH1D*)f2->Get("expert/FullBkg_d0_pulls");
    //TH1D *h2= (TH1D*)f2->Get("expert/FullBkg_omega_estimates");
    //TH1D *h2= (TH1D*)f2->Get("expert/FullBkg_omega_pulls");
    //TH1D *h2= (TH1D*)f2->Get("expert/FullBkg_tan_lambda_estimates");
    //TGraphErrors *h2= (TGraphErrors*)f2->Get("expert/FullBkg_pt_res_resolution");
    //TGraphErrors *h2= (TGraphErrors*)f2->Get("expert/FullBkg_z0_res_resolution");
    //TGraphErrors *h2= (TGraphErrors*)f2->Get("expert/FullBkg_d0_res_resolution");
    //h2->SetStats(0);
    h2->Draw("");
    //h2->Draw("E SAME");
    //h2->SetLineWidth(1);
    h2->SetLineColor(2);
       
    TFile *f1 = TFile::Open("noL3_Side0_1000evts_PXDredON_FullTrackingValidationBkg.root");
    TH1D *h1= (TH1D*)f1->Get("FullBkg_finding_efficiency_by_phi");
    //TH1D *h1= (TH1D*)f1->Get("FullBkg_finding_efficiency_by_theta");
    //TH1D *h1= (TH1D*)f1->Get("FullBkg_hit_efficiency_with_matched_tracks_by_phi");
    //TH1D *h1= (TH1D*)f1->Get("FullBkg_hit_efficiency_with_matched_tracks_by_theta");
    //TH1D *h1= (TH1D*)f1->Get("FullBkg_finding_and_charge_efficiency_for_primary_tracks_by_phi");
    //TH1D *h1= (TH1D*)f1->Get("expert/FullBkg_z0_res_resolution");
    //TH1D *h1= (TH1D*)f1->Get("expert/FullBkg_d0_estimates");
    //TH1D *h1= (TH1D*)f1->Get("expert/FullBkg_d0_pulls");
    //TH1D *h1= (TH1D*)f1->Get("expert/FullBkg_omega_estimates");
    //TH1D *h1= (TH1D*)f1->Get("expert/FullBkg_omega_pulls");
    //TH1D *h1= (TH1D*)f1->Get("expert/FullBkg_tan_lambda_estimates");
    //TGraphErrors *h1= (TGraphErrors*)f1->Get("expert/FullBkg_pt_res_resolution");
    //TGraphErrors *h1= (TGraphErrors*)f1->Get("expert/FullBkg_z0_res_resolution");
    //TGraphErrors *h1= (TGraphErrors*)f1->Get("expert/FullBkg_d0_res_resolution");
    //h1->SetStats(0);
    h1->Draw("same");
    //h1->Draw("E");
    //h1->SetLineWidth(1);
    h1->SetLineColor(3);
    
    TFile *f3 = TFile::Open("noL3_Side1_1000evts_PXDredON_FullTrackingValidationBkg.root");
    TH1D *h3= (TH1D*)f3->Get("FullBkg_finding_efficiency_by_phi");
    //TH1D *h3= (TH1D*)f3->Get("FullBkg_finding_efficiency_by_theta");
    //TH1D *h3= (TH1D*)f3->Get("FullBkg_hit_efficiency_with_matched_tracks_by_phi");
    //TH1D *h3= (TH1D*)f3->Get("FullBkg_hit_efficiency_with_matched_tracks_by_theta");
    //TH1D *h3= (TH1D*)f3->Get("FullBkg_finding_and_charge_efficiency_for_primary_tracks_by_phi");
    //TH1D *h3= (TH1D*)f3->Get("expert/FullBkg_z0_res_resolution");
    //TH1D *h3= (TH1D*)f3->Get("expert/FullBkg_d0_estimates");
    //TH1D *h3= (TH1D*)f3->Get("expert/FullBkg_d0_pulls");
    //TH1D *h3= (TH1D*)f3->Get("expert/FullBkg_omega_estimates");
    //TH1D *h3= (TH1D*)f3->Get("expert/FullBkg_omega_pulls");
    //TH1D *h3= (TH1D*)f3->Get("expert/FullBkg_tan_lambda_estimates");
    //TGraphErrors *h3= (TGraphErrors*)f3->Get("expert/FullBkg_pt_res_resolution");
    //TGraphErrors *h3= (TGraphErrors*)f3->Get("expert/FullBkg_z0_res_resolution");
    //TGraphErrors *h3= (TGraphErrors*)f3->Get("expert/FullBkg_d0_res_resolution");
    //h3->SetStats(0);
    h3->Draw("same");
    //h1->Draw("E");
    //h1->SetLineWidth(1);
    h3->SetLineColor(4);
    
    TFile *f4 = TFile::Open("noL3Lad34_Side0_1000evts_PXDredON_FullTrackingValidationBkg.root");
    TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_efficiency_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_efficiency_by_theta");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_hit_efficiency_with_matched_tracks_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_hit_efficiency_with_matched_tracks_by_theta");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_and_charge_efficiency_for_primary_tracks_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_z0_res_resolution");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_d0_estimates");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_d0_pulls");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_omega_estimates");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_omega_pulls");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_tan_lambda_estimates");
    //TGraphErrors *h4= (TGraphErrors*)f4->Get("expert/FullBkg_pt_res_resolution");
    //TGraphErrors *h4= (TGraphErrors*)f4->Get("expert/FullBkg_z0_res_resolution");
    //TGraphErrors *h4= (TGraphErrors*)f4->Get("expert/FullBkg_d0_res_resolution");
    //h4->SetStats(0);
    h4->Draw("same");
    //h1->Draw("E");
    //h1->SetLineWidth(1);
    h4->SetLineColor(6);
    
    TFile *f5 = TFile::Open("noL3Lad34_Side1_1000evts_PXDredON_FullTrackingValidationBkg.root");
    TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_efficiency_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_efficiency_by_theta");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_hit_efficiency_with_matched_tracks_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_hit_efficiency_with_matched_tracks_by_theta");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_and_charge_efficiency_for_primary_tracks_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_z0_res_resolution");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_d0_estimates");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_d0_pulls");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_omega_estimates");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_omega_pulls");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_tan_lambda_estimates");
    //TGraphErrors *h5= (TGraphErrors*)f5->Get("expert/FullBkg_pt_res_resolution");
    //TGraphErrors *h5= (TGraphErrors*)f5->Get("expert/FullBkg_z0_res_resolution");
    //TGraphErrors *h5= (TGraphErrors*)f5->Get("expert/FullBkg_d0_res_resolution");
    //h4->SetStats(0);
    h5->Draw("same");
    //h1->Draw("E");
    //h1->SetLineWidth(1);
    h5->SetLineColor(8);
    
    TFile *f6 = TFile::Open("noL3Lad2345_Side0_1000evts_PXDredON_FullTrackingValidationBkg.root");
    TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_efficiency_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_efficiency_by_theta");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_hit_efficiency_with_matched_tracks_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_hit_efficiency_with_matched_tracks_by_theta");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_and_charge_efficiency_for_primary_tracks_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_z0_res_resolution");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_d0_estimates");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_d0_pulls");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_omega_estimates");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_omega_pulls");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_tan_lambda_estimates");
    //TGraphErrors *h6= (TGraphErrors*)f6->Get("expert/FullBkg_pt_res_resolution");
    //TGraphErrors *h6= (TGraphErrors*)f6->Get("expert/FullBkg_z0_res_resolution");
    //TGraphErrors *h6= (TGraphErrors*)f6->Get("expert/FullBkg_d0_res_resolution");
    //h4->SetStats(0);
    h6->Draw("same");
    //h1->Draw("E");
    //h1->SetLineWidth(1);
    h6->SetLineColor(9);
    
    TFile *f7 = TFile::Open("noL3Lad2345_Side1_1000evts_PXDredON_FullTrackingValidationBkg.root");
    TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_efficiency_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_efficiency_by_theta");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_hit_efficiency_with_matched_tracks_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_hit_efficiency_with_matched_tracks_by_theta");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_and_charge_efficiency_for_primary_tracks_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_z0_res_resolution");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_d0_estimates");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_d0_pulls");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_omega_estimates");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_omega_pulls");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_tan_lambda_estimates");
    //TGraphErrors *h7= (TGraphErrors*)f7->Get("expert/FullBkg_pt_res_resolution");
    //TGraphErrors *h7= (TGraphErrors*)f7->Get("expert/FullBkg_z0_res_resolution");
    //TGraphErrors *h7= (TGraphErrors*)f7->Get("expert/FullBkg_d0_res_resolution");
    //h4->SetStats(0);
    h7->Draw("same");
    //h1->Draw("E");
    //h1->SetLineWidth(1);
    h7->SetLineColor(12);
    
    TFile *f8 = TFile::Open("noL3_1000evts_PXDredON_FullTrackingValidationBkg.root");
    TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_efficiency_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_efficiency_by_theta");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_hit_efficiency_with_matched_tracks_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_hit_efficiency_with_matched_tracks_by_theta");
    //TH1D *h4= (TH1D*)f4->Get("FullBkg_finding_and_charge_efficiency_for_primary_tracks_by_phi");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_z0_res_resolution");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_d0_estimates");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_d0_pulls");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_omega_estimates");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_omega_pulls");
    //TH1D *h4= (TH1D*)f4->Get("expert/FullBkg_tan_lambda_estimates");
    //TGraphErrors *h8= (TGraphErrors*)f8->Get("expert/FullBkg_pt_res_resolution");
    //TGraphErrors *h8= (TGraphErrors*)f8->Get("expert/FullBkg_z0_res_resolution");
    //TGraphErrors *h8= (TGraphErrors*)f8->Get("expert/FullBkg_d0_res_resolution");
    //h4->SetStats(0);
    h8->Draw("same");
    //h1->Draw("E");
    //h1->SetLineWidth(1);
    h8->SetLineColor(15);
    
    TLegend *leg = new TLegend(0.2,0.2,0.3,0.3);
    leg->AddEntry(h2,"No Layer Masked","l");
    leg->AddEntry(h8,"L3 complete Masked","l");
    leg->AddEntry(h1,"L3 side 0 masked","l");
    leg->AddEntry(h3,"L3 side 1 masked","l");
    leg->AddEntry(h4,"noL3Lad34 side 0 masked","l");
    leg->AddEntry(h5,"noL3Lad34 side 1 masked","l");
    leg->AddEntry(h6,"noL3Lad2345 side 0 masked","l");
    leg->AddEntry(h7,"noL3Lad2345 side 1 masked","l");
    leg->Draw();
}
 

